name: fraud-detection-env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
      - pandas==2.0.3
      - numpy==1.24.3
      - scikit-learn==1.3.1
      - xgboost==2.0.0
      - imbalanced-learn==0.11.0

      # MLOps
      - dvc[azure]==3.51.2
      - mlflow==2.9.2

      # API
      - fastapi==0.104.1
      - uvicorn==0.24.0
      - pydantic==2.3.0

      # Monitoring
      - evidently==0.7.18

      # Utils
      - pyyaml==6.0.1
      - python-dotenv==1.0.0
      - requests
