stages:
  preprocess:
    cmd: python -m pipelines.train_pipeline --stage preprocess
    deps:
      - data/raw/creditcard.csv
      - src/data/
      - src/features/
      - src/utils/
      - pipelines/train_pipeline.py
    outs:
      - data/processed/
      - artifacts/scaler.pkl

  train:
    cmd: python -m pipelines.train_pipeline --stage train
    deps:
      - data/processed/
      - artifacts/scaler.pkl
      - src/models/
      - src/evaluation/
      - src/utils/
      - pipelines/train_pipeline.py
    outs:
      - artifacts/model.pkl
    # metrics:
    #   - metrics/training_metrics.json

  evaluate:
    cmd: python -m pipelines.evaluate_pipeline
    deps:
      - artifacts/model.pkl
      - data/processed/
      - src/evaluation/
      - src/utils/
      - pipelines/evaluate_pipeline.py
    metrics:
      - metrics/evaluation_metrics.json
    plots:
      - metrics/roc_curve.csv:
          x: fpr
          y: tpr

  drift_check:
    cmd: python -m pipelines.drift_pipeline
    deps:
      - data/reference/
      - data/incoming/
      - src/monitoring/
      - pipelines/drift_pipeline.py
    metrics:
      - reports/drift/drift_metrics.json
