stages:
  preprocess:
    cmd: python -m pipelines.train_pipeline.py --stage preprocess
    deps:
      - data/raw.dvc
      - src/data
      - src/features
      - src/utils
      - pipelines.train_pipeline.py
    outs:
      - data/processed

  train:
    cmd: python -m pipelines.train_pipeline.py --stage train
    deps:
      - data/processed
      - src/models
      - src/evaluation
      - src/utils
      - pipelines.train_pipeline.py
    metrics:
      - metrics/training_metrics.json

  evaluate:
    cmd: python -m pipelines.evaluate_pipeline.py
    deps:
      - data/processed
      - src/evaluation
      - src/utils
      - pipelines.evaluate_pipeline.py
    metrics:
      - metrics/evaluation_metrics.json
    plots:
      - metrics/roc_curve.csv:
          x: fpr
          y: tpr

  drift_check:
    cmd: python -m pipelines.drift_pipeline.py
    deps:
      - data/reference.dvc
      - data/incoming.dvc
      - src/monitoring
      - pipelines.drift_pipeline.py
    metrics:
      - reports/drift/drift_metrics.json
