stages:
  preprocess:
    cmd: python -m pipelines.train_pipeline --stage preprocess --raw-data data/raw/creditcard.csv
    deps:
      - pipelines/train_pipeline.py
      - src/data
      - data/raw/creditcard.csv
      - params.yaml
    outs:
      - data/processed
      - artifacts/scaler.pkl

  train:
    cmd: python -m pipelines.train_pipeline --stage train --raw-data data/raw/creditcard.csv
    deps:
      - pipelines/train_pipeline.py
      - src/models
      - src/features
      - src/evaluation
      - src/utils
      - data/processed
      - artifacts/scaler.pkl
      - params.yaml
    outs:
      - artifacts/model.pkl
      - artifacts/metrics.json
      - artifacts/cv_scores.json
      - artifacts/threshold.json

  evaluate:
    cmd: python -m pipelines.evaluate_pipeline
    deps:
      - pipelines/evaluate_pipeline.py
      - src/inference
      - src/evaluation
      - artifacts/model.pkl
      - artifacts/scaler.pkl
    outs:
      - artifacts/evaluation_metrics.json

