stages:
  preprocess:
    cmd: python -m pipelines.train_pipeline --stage preprocess --data-path 
      data/raw/creditcard.csv
    deps:
    - data/raw/creditcard.csv
    - pipelines/train_pipeline.py
    - src
    params:
    - data
    - features
    outs:
    - artifacts/scaler.pkl
    - data/processed
  train:
    cmd: python -m pipelines.train_pipeline --stage train
    deps:
    - artifacts/scaler.pkl
    - data/processed
    - pipelines/train_pipeline.py
    - src
    outs:
    - artifacts/cv_scores.json
    - artifacts/metrics.json
    - artifacts/model.pkl
    - artifacts/threshold.json
    params:
    - evaluation
    - features
    - model
  evaluate:
    cmd: python -m pipelines.evaluate_pipeline
    deps:
    - artifacts/model.pkl
    - artifacts/scaler.pkl
    - data/processed
    - pipelines/evaluate_pipeline.py
    - src
    outs:
    - artifacts/evaluation_metrics.json
  drift_check:
    cmd: python -m pipelines.drift_pipeline
    deps:
    - data/incoming
    - data/reference
    - pipelines/drift_pipeline.py
    - src
    outs:
    - artifacts/drift_report.json
